name: digital_shield
description: "AI-Powered Anti-Scam Protection for Digital Arrest Scams."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  speech_to_text: ^7.3.0
  flutter_background_service: ^5.0.10
  permission_handler: ^11.3.1
  camera: ^0.11.0
  google_generative_ai: ^0.4.3
  flutter_overlay_window: ^0.5.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  device_info_plus: ^10.1.2
  vibration: ^3.1.7
  audioplayers: ^6.1.1
  android_intent_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

